query GetUser {
  getUser {
    id
    firstName
    lastName
    email
    createdAt
    updatedAt
  }
}

mutation GoogleSignIn($googleToken: String!) {
  googleSignIn(googleToken: $googleToken) {
    id
    firstName
    email
    lastName
    createdAt
    updatedAt
  }
}
